### ISSUE TITLE
add css ui kit

### ISSUE THREAD

**Issue by contra** [FACTORYX/stack#45]
something like uikit, semantic, elemental, etc.

**Comment by funkytek** [comment]
doing some research - I like the look of semantic the best but it does mean using jquery inside of components, going to try it out

**Comment by funkytek** [comment]
Looked through everything, imo Semantic is far and away the best looking, but uses jquery.  https://github.com/jessy1092/react-semantify is the best attempt around wrapping semantic in react components and I'm playing with it now vs. raw semantic

React-Toolbox seems pretty ok but I personally don't really like material design
http://react-toolbox.com/#/components
