### ISSUE TITLE
Webpack dev: missing dependencies do not return error

### ISSUE THREAD

**Issue by stevelacy** [FACTORYX/stack#64]
`webpack-dev-middleware`: no error is shown or thrown if there are missing dependencies listed in the webpack config.

The only way I could determine why the build failed (due to not installed deps) was to add the error handler hook:

```js
import webpackConfig from '../../../../webpack'
const compiler = webpack(webpackConfig, function(err, stats) {
  if (stats.compilation.missingDependencies[0]) {
    throw new Error('missing webpack config dependencies ' + JSON.stringify(stats.compilation.missingDependencies, null, 2))
  }

})
```
the `err` does not return an error for logical or build errors.

@contra should we create an error handler for that middleware?

**Comment by contra** [comment]
@stevelacy strange, go ahead and PR
