### ISSUE TITLE
[shasta/tahoe] figure out paging functionality for tahoe + cursors

### ISSUE THREAD

**Issue by contra** [FACTORYX/stack#74]
blocked by #70

**Comment by funkytek** [comment]
https://github.com/rackt/redux/blob/ecb1bb453a60408543f5760bba0aa4c767650ba2/examples/real-world/reducers/paginate.js

**Comment by contra** [comment]
Solution:

- dynamic storeProps functions receive page state from either props (incl the router) or the central store
- tahoe and sutro support page # in the querystring
